Portfolie Mobile version Last section completed
ademibowale/my-portfolio1 pull request #1
Opened 2022-04-25 16:56 UTC by ademibowale

Portfolio: mobile version
Learning objectives
Understand how to parse a Figma design to create a UI.
Use Flexbox to place elements in the page.
Use CSS Grid to place elements in the page.
Build a personal portfolio site.

2022-04-25 20:24 UTC, prolajumokeoni requested changes
Hi @ademibowale, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 
-  I advise you use the same repository and different pull request for each milestone, this will help the reviewer understand the pr better, please use the same pull request for re review, when it is approved the you can merge and move to the next milestone  on a new pr👍🏿  
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 20:24 UTC, prolajumokeoni commented on index.html
> +        <h2 class="works">My Recent Works</h2>
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_75](https://user-images.githubusercontent.com/69638013/165166928-7e29eef2-e908-45cf-a6b0-4fe19dd8deec.png)  |  ![Screenshot_74](https://user-images.githubusercontent.com/69638013/165167006-437a27ec-3c26-4329-b810-6c6eecbbeecf.png)

- [ ] Kindly add the horizontal line after my recent works heading 👍🏿

2022-04-25 20:24 UTC, prolajumokeoni commented on index.html
> +        <h2 class="works">My Recent Works</h2>
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_75](https://user-images.githubusercontent.com/69638013/165166928-7e29eef2-e908-45cf-a6b0-4fe19dd8deec.png)  |  ![Screenshot_74](https://user-images.githubusercontent.com/69638013/165167006-437a27ec-3c26-4329-b810-6c6eecbbeecf.png)

- [ ] Kindly add the horizontal line after my recent works heading 👍🏿

2022-04-25 20:24 UTC, prolajumokeoni commented on index.html
> +    <section class="work-section">
- [ ] Kindly add the add button styling: Active, Hover and Pressed (see screenshot)

![Screenshot_76](https://user-images.githubusercontent.com/69638013/165167605-f0697c39-410c-4fa3-97b0-88aa7f5eb253.png)

- Please make this adjustment for all the  buttons in this section👍🏿

2022-04-25 20:24 UTC, prolajumokeoni commented on index.html
> +            <button class="button about-button" type="button">Get My Resume</button>
- [ ] Kindly add the add button styling: Active, Hover and Pressed (see screenshot)

![Screenshot_76](https://user-images.githubusercontent.com/69638013/165167605-f0697c39-410c-4fa3-97b0-88aa7f5eb253.png)

2022-04-28 21:35 UTC, codepantha approved these changes
Hi @ademibowale 👋,

## STATUS: APPROVED ✔️  

Great work on making the changes requested by the previous reviewer 👏 
Your project is now complete.

<img src="https://media4.giphy.com/media/nBaHkYEzY7N0SlQSAa/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 08:50 UTC, merged