Mobile contact form
ademibowale/my-portfolio1 pull request #2
Opened 2022-05-03 09:35 UTC by ademibowale

this is contact form for the mobile -portfolio project

2022-05-03 12:42 UTC, ademibowale commented
completion of mobile project ,
adding a contact form to make it complete.

2022-05-03 12:53 UTC, keroloussamy requested changes
Hi @ademibowale, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 12:53 UTC, keroloussamy commented on index.html
> +        <form class="form" action="/form/submit" method="POST">
- [ ] Kindly you have to use [formspree service](https://formspree.io/html), the `action` value should be similar to `https://formspree.io/f/{form_id}`.

2022-05-03 12:53 UTC, keroloussamy commented on index.html
> +            <input type="text" id="fname" name="name" placeholder="Full Name">
- [ ] Kindly the name input should have the `maxlength="30"` attribute.
- [ ] Kindly the name input should have the `required` attribute.

2022-05-03 12:53 UTC, keroloussamy commented on index.html
> +            <input type="text" id="mail" name="e-mail" placeholder="Email">
- [ ] Kindly the name input should have the `type` attribute equal to `email` not `text`.
- [ ] Kindly the name input should have the `required` attribute.

2022-05-03 12:53 UTC, keroloussamy commented on index.html
> +            <textarea name="message" cols="30" rows="10">Enter Yout text here</textarea>
- [ ] Kindly the name input should have the `maxlength="500"` attribute.
- [ ] Kindly the name input should have the `required` attribute.

2022-05-04 09:29 UTC, ademibowale commented
i have made changes on the error thank you .

2022-05-04 09:52 UTC, m05e5 requested changes
Hi @ademibowale , 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve
Please sorry if the previous reviewer didn't mention it but there are some main requirements you have to follow.

- [ ] Hi Please kindly fix your design so it can match the one on figma 
**your design**

![image](https://user-images.githubusercontent.com/37901469/166659769-72d5c746-7886-4790-8fa3-1f69bb8627c9.png)

**figma design**
![image](https://user-images.githubusercontent.com/37901469/166659952-2cda9999-798d-4135-ba69-8df2ba48df91.png)

- _Please check the comments below_

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 09:52 UTC, m05e5 commented on index.html
> +        <button class="get-button" type="button">Get In Touch</button>
- [ ] Hi. Please your form is supposed to have a `submit` button. Please kindly put the `get in touch` button in your form and change the type to `submit`
When you're done please test it by sending a message and see if you effectively get the mail.

2022-05-04 09:52 UTC, m05e5 commented on index.html
> +            <input id="email" name="email" type="email" placeholder="Email">
- [ ] As mentioned by the previous reviewer, please add a `required` to your email input. The email address of the person is very important because you need it to be able to reply to his message.

2022-05-04 12:56 UTC, ademibowale commented
done with all required changes.

2022-05-05 07:54 UTC, merged